language: generic 

sudo:required #WE NEED SUPER USER PERMISSIONS
services:
  - docker #need copy of docker

before_install:
  - docker build -t glovass/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true glovass/docker-react npm run test
